### ISSUE TITLE
LiDAR Motion Distortion

### ISSUE THREAD

**Issue by patripfr** [Cosys-Lab/Cosys-AirSim#3]
Hi,
I saw that this version of AirSim contains an updated LiDAR sensor model, which is great :) I was wondering if it also supports realistic motion distortion, like the one you would see in the output from a real-life LiDAR?

**Comment by WouterJansen** [comment]
The GPU accelerated LiDAR that we added somewhat implements motion distortion in that each frame calculates only the points based on the time that has past since the last calculation so in that way yes it will be more accurate for motion distortion from the movement of the lidar itself and the objects surrounding it. 

The same thing applies to the existing AirSim LiDAR sensor (using CPU collisions) which we also upgraded and applies the same principle of only calculating the points based on the time delta that has passed between consecutive frames.

**Comment by patripfr** [comment]
Thanks for the clarification! :)
